import { PageHero } from "../components/common/PageHero";
import { SectionCard } from "../components/ui/SectionCard";
import { useAsyncData } from "../hooks/useAsyncData";
import { api } from "../lib/api";
import { DataState } from "../components/ui/DataState";
import { DataTable } from "../components/ui/DataTable";
import { StatusBadge } from "../components/ui/StatusBadge";
import { formatDate } from "../lib/formatters";

export function NotificationsPage() {
  const notifications = useAsyncData(async () => {
    const response = await api.get("/notifications");
    return response.data.data;
  }, []);

  const rows =
    notifications.data?.map((item) => ({
      id: item._id,
      title: item.title,
      message: item.message,
      type: item.type,
      created: formatDate(item.createdAt)
    })) || [];

  return (
    <div className="page-stack">
      <PageHero title="Notifications" description="In-app updates for verification decisions, request progress, and resource status changes." />
      <SectionCard eyebrow="Inbox" title="Recent updates" description="These records are generated by backend workflow actions.">
        <DataState isLoading={notifications.isLoading} error={notifications.error} empty={!rows.length}>
          <DataTable
            columns={[
              { key: "title", label: "Title" },
              { key: "message", label: "Message" },
              { key: "type", label: "Type", render: (row) => <StatusBadge value={row.type} /> },
              { key: "created", label: "Created" }
            ]}
            rows={rows}
          />
        </DataState>
      </SectionCard>
    </div>
  );
}
